### PR TITLE
Windows fixes

### PR DESCRIPTION
**Pull request by Hakuna75**
The script didn't run under Windows (8.1) anymore

* FIX: running under Windows gave a symlink error for every touched file
* FIX: running under Windows in Git workdir skipped all files - pathspec outside work tree

### CODE REVIEW

**Comment by MestreLion** [comment]
Thanks for spotting and reporting those bugs!

I can see my mistake when I changed the logic on `follow_symlinks`. But I believe a better fix would be to follow the original idea from bb98523e26cc641f203b350c7d46251c3e79c5fc: a single `if` test to check OS support, that defines `touch()` with or without `follow_symlinks`. This way, when `touch()` is called in the hiper-sensitive `parselog()` loop it will not perform any tests. Care to change that to something along this?

```py
# Right after the imports, now as a global constant:

# Update symlinks only if the OS has support on not following them
UPDATE_SYMLINKS = bool(os.utime in getattr(os, 'supports_follow_symlinks', []))  

...

# On touch() definition:
if UPDATE_SYMLINKS:
    def touch(path, mtime, test=False):
        """The actual mtime update"""
        if test: return
        os.utime(path, (mtime, mtime), follow_symlinks=False)
else:
    def touch(path, mtime, test=False):
        """The actual mtime update"""
        if test: return
        os.utime(path, (mtime, mtime))
```
Then remove the former `update_symlinks` definition down the code, and replace all occurrences with `UPDATE_SYMLINKS`

**Comment by MestreLion** [comment]
As for the other fix, thanks again for spotting and reporting!

But instead of hardcoding a bunch of `.replace()`, maybe it's better to fix the root issue: if `git` always output paths using Unix forward slashes, we can simply `os.path.normpath()` inside `Git.repodirs()`, similar to what `Git.ls_files()` does:

```py
def repodirs(self):
    return (os.path.normpath(_) for _ in self._run('rev-parse --show-toplevel --absolute-git-dir', check=True))
```

Care to check if this fixes all path mismatches?

**Comment by Hakuna75** [comment]
OK, I'll try to get it done today; I'll rewrite the current commits and send you a pull request later.

Regards,

Remco


________________________________

**Comment by Hakuna75** [comment]
I'll try it out and get back to you.

Regards,

Remco

________________________________

**Pull request closed without merging**
